package com.cowboysmall.scratch.cartrawler.repository;

import com.cowboysmall.scratch.cartrawler.model.CarResult;
import com.cowboysmall.scratch.cartrawler.model.FuelPolicy;

import java.util.ArrayList;
import java.util.List;


public class CarResultRepositoryImpl implements CarResultRepository {

    @Override
    public List<CarResult> getAllCarResults() {

        List<CarResult> carResults = new ArrayList<>();
        carResults.add(new CarResult("Volkswagen Polo", "NIZA", "EDMR", FuelPolicy.FULLEMPTY, 12.81d));
        carResults.add(new CarResult("Ford C-Max Diesel", "NIZA", "CMMD", FuelPolicy.FULLEMPTY, 22.04d));
        carResults.add(new CarResult("Renault Scenic Diesel", "NIZA", "JGAD", FuelPolicy.FULLEMPTY, 93.67d));
        carResults.add(new CarResult("Volkswagen Up", "NIZA", "MDMR", FuelPolicy.FULLEMPTY, 9.78d));
        carResults.add(new CarResult("Volkswagen Golf", "NIZA", "CDMR", FuelPolicy.FULLEMPTY, 18.07d));
        carResults.add(new CarResult("Audi A3 Diesel", "NIZA", "CDMD", FuelPolicy.FULLEMPTY, 41.16d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "NIZA", "IVMD", FuelPolicy.FULLEMPTY, 55.47d));
        carResults.add(new CarResult("Mini Cooper", "NIZA", "EDMR", FuelPolicy.FULLEMPTY, 16.75d));
        carResults.add(new CarResult("BMW 2 Series Gran Tourer Diesel", "NIZA", "JVAD", FuelPolicy.FULLFULL, 146.62d));
        carResults.add(new CarResult("Volkswagen Polo", "NIZA", "EDMR", FuelPolicy.FULLFULL, 22.65d));
        carResults.add(new CarResult("Ford C-Max Diesel", "NIZA", "CMMD", FuelPolicy.FULLFULL, 43.98d));
        carResults.add(new CarResult("Renault Scenic Diesel", "NIZA", "JGAD", FuelPolicy.FULLFULL, 115.58d));
        carResults.add(new CarResult("Volkswagen Up", "NIZA", "MDMR", FuelPolicy.FULLFULL, 18.6d));
        carResults.add(new CarResult("Volkswagen Golf", "NIZA", "CDMR", FuelPolicy.FULLFULL, 33.06d));
        carResults.add(new CarResult("Audi A3 Diesel", "NIZA", "CDMD", FuelPolicy.FULLFULL, 63.07d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "NIZA", "IVMD", FuelPolicy.FULLFULL, 77.41d));
        carResults.add(new CarResult("Mini Cooper", "NIZA", "EDMR", FuelPolicy.FULLFULL, 36.92d));
        carResults.add(new CarResult("Citroen Berlingo", "CENTAURO", "CMMV", FuelPolicy.FULLEMPTY, 33.15d));
        carResults.add(new CarResult("Ford Focus Estate Diesel", "CENTAURO", "CWMD", FuelPolicy.FULLEMPTY, 67.26d));
        carResults.add(new CarResult("Volkswagen Golf", "CENTAURO", "CDMR", FuelPolicy.FULLEMPTY, 26.96d));
        carResults.add(new CarResult("Ford Fiesta Diesel", "CENTAURO", "EDMD", FuelPolicy.FULLEMPTY, 25.02d));
        carResults.add(new CarResult("Nissan Juke Diesel", "CENTAURO", "HFMD", FuelPolicy.FULLEMPTY, 34.32d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "CENTAURO", "CDMD", FuelPolicy.FULLEMPTY, 40.91d));
        carResults.add(new CarResult("Ford C-Max Diesel", "CENTAURO", "CMMD", FuelPolicy.FULLEMPTY, 69.2d));
        carResults.add(new CarResult("Volkswagen Touran", "CENTAURO", "IVAR", FuelPolicy.FULLEMPTY, 99.8d));
        carResults.add(new CarResult("Volkswagen Polo", "CENTAURO", "EDMR", FuelPolicy.FULLEMPTY, 11.08d));
        carResults.add(new CarResult("Ford Focus Estate", "CENTAURO", "CWMR", FuelPolicy.FULLEMPTY, 59.12d));
        carResults.add(new CarResult("Ford Galaxy Diesel", "CENTAURO", "FVMD", FuelPolicy.FULLEMPTY, 148.23d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "CENTAURO", "SVMR", FuelPolicy.FULLEMPTY, 163.73d));
        carResults.add(new CarResult("Volkswagen Touran", "CENTAURO", "IVMR", FuelPolicy.FULLEMPTY, 72.29d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "CENTAURO", "IVMD", FuelPolicy.FULLEMPTY, 80.43d));
        carResults.add(new CarResult("Peugeot 107", "CENTAURO", "MCMR", FuelPolicy.FULLEMPTY, 9.53d));
        carResults.add(new CarResult("Citroen Berlingo", "CENTAURO", "CMMV", FuelPolicy.FULLFULL, 65.15d));
        carResults.add(new CarResult("Ford Focus Estate Diesel", "CENTAURO", "CWMD", FuelPolicy.FULLFULL, 100.27d));
        carResults.add(new CarResult("Volkswagen Golf", "CENTAURO", "CDMR", FuelPolicy.FULLFULL, 58.77d));
        carResults.add(new CarResult("Ford Fiesta Diesel", "CENTAURO", "EDMD", FuelPolicy.FULLFULL, 56.77d));
        carResults.add(new CarResult("Nissan Juke Diesel", "CENTAURO", "HFMD", FuelPolicy.FULLFULL, 66.35d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "CENTAURO", "CDMD", FuelPolicy.FULLFULL, 73.14d));
        carResults.add(new CarResult("Ford C-Max Diesel", "CENTAURO", "CMMD", FuelPolicy.FULLFULL, 102.27d));
        carResults.add(new CarResult("Volkswagen Touran", "CENTAURO", "IVAR", FuelPolicy.FULLFULL, 133.79d));
        carResults.add(new CarResult("Volkswagen Polo", "CENTAURO", "EDMR", FuelPolicy.FULLFULL, 42.41d));
        carResults.add(new CarResult("Ford Focus Estate", "CENTAURO", "CWMR", FuelPolicy.FULLFULL, 91.89d));
        carResults.add(new CarResult("Ford Galaxy Diesel", "CENTAURO", "FVMD", FuelPolicy.FULLFULL, 183.66d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "CENTAURO", "SVMR", FuelPolicy.FULLFULL, 199.62d));
        carResults.add(new CarResult("Volkswagen Touran", "CENTAURO", "IVMR", FuelPolicy.FULLFULL, 105.45d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "CENTAURO", "IVMD", FuelPolicy.FULLFULL, 113.83d));
        carResults.add(new CarResult("Peugeot 107", "CENTAURO", "MCMR", FuelPolicy.FULLFULL, 40.82d));
        carResults.add(new CarResult("Citroen Berlingo", "CENTAURO", "CMMV", FuelPolicy.FULLEMPTY, 34.11d));
        carResults.add(new CarResult("Ford Focus Estate Diesel", "CENTAURO", "CWMD", FuelPolicy.FULLEMPTY, 69.24d));
        carResults.add(new CarResult("Volkswagen Golf", "CENTAURO", "CDMR", FuelPolicy.FULLEMPTY, 27.73d));
        carResults.add(new CarResult("Ford Fiesta Diesel", "CENTAURO", "EDMD", FuelPolicy.FULLEMPTY, 25.74d));
        carResults.add(new CarResult("Nissan Juke Diesel", "CENTAURO", "HFMD", FuelPolicy.FULLEMPTY, 35.31d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "CENTAURO", "CDMD", FuelPolicy.FULLEMPTY, 42.1d));
        carResults.add(new CarResult("Ford C-Max Diesel", "CENTAURO", "CMMD", FuelPolicy.FULLEMPTY, 71.23d));
        carResults.add(new CarResult("Volkswagen Touran", "CENTAURO", "IVAR", FuelPolicy.FULLEMPTY, 102.75d));
        carResults.add(new CarResult("Volkswagen Polo", "CENTAURO", "EDMR", FuelPolicy.FULLEMPTY, 11.38d));
        carResults.add(new CarResult("Ford Focus Estate", "CENTAURO", "CWMR", FuelPolicy.FULLEMPTY, 60.86d));
        carResults.add(new CarResult("Ford Galaxy Diesel", "CENTAURO", "FVMD", FuelPolicy.FULLEMPTY, 152.63d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "CENTAURO", "SVMR", FuelPolicy.FULLEMPTY, 168.59d));
        carResults.add(new CarResult("Volkswagen Touran", "CENTAURO", "IVMR", FuelPolicy.FULLEMPTY, 74.42d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "CENTAURO", "IVMD", FuelPolicy.FULLEMPTY, 82.8d));
        carResults.add(new CarResult("Peugeot 107", "CENTAURO", "MCMR", FuelPolicy.FULLEMPTY, 9.78d));
        carResults.add(new CarResult("Toyota Avensis", "GOLDCAR", "IDMR", FuelPolicy.FULLEMPTY, 301.95d));
        carResults.add(new CarResult("Nissan Juke", "GOLDCAR", "CFMR", FuelPolicy.FULLEMPTY, 146.54d));
        carResults.add(new CarResult("Volkswagen Golf", "GOLDCAR", "CLMR", FuelPolicy.FULLEMPTY, 52.02d));
        carResults.add(new CarResult("Citroen C4 Grand Picasso", "GOLDCAR", "IVAR", FuelPolicy.FULLEMPTY, 399.28d));
        carResults.add(new CarResult("Toyota Avensis", "GOLDCAR", "IDAR", FuelPolicy.FULLEMPTY, 116.68d));
        carResults.add(new CarResult("Ford Focus Estate", "GOLDCAR", "CWMR", FuelPolicy.FULLEMPTY, 126.08d));
        carResults.add(new CarResult("Volkswagen Touran", "GOLDCAR", "IVMR", FuelPolicy.FULLEMPTY, 366.84d));
        carResults.add(new CarResult("Citroen DS3", "GOLDCAR", "ESMR", FuelPolicy.FULLEMPTY, 63.69d));
        carResults.add(new CarResult("Audi A3", "GOLDCAR", "ICMR", FuelPolicy.FULLEMPTY, 84.46d));
        carResults.add(new CarResult("Citroen Berlingo", "GOLDCAR", "CMMV", FuelPolicy.FULLEMPTY, 53.89d));
        carResults.add(new CarResult("Volkswagen Polo", "GOLDCAR", "EDMR", FuelPolicy.FULLEMPTY, 31.71d));
        carResults.add(new CarResult("Renault Scenic", "GOLDCAR", "JGMR", FuelPolicy.FULLEMPTY, 139.95d));
        carResults.add(new CarResult("BMW 3 Series", "GOLDCAR", "FDAR", FuelPolicy.FULLEMPTY, 436.43d));
        carResults.add(new CarResult("Peugeot 107", "GOLDCAR", "MCMR", FuelPolicy.FULLEMPTY, 26.86d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "GOLDCAR", "SVMR", FuelPolicy.FULLEMPTY, 621.7d));
        carResults.add(new CarResult("Volkswagen Golf", "GOLDCAR", "CDMR", FuelPolicy.FULLEMPTY, 39.79d));
        carResults.add(new CarResult("Toyota Avensis", "GOLDCAR", "IDMR", FuelPolicy.FULLFULL, 243.55d));
        carResults.add(new CarResult("Nissan Juke", "GOLDCAR", "CFMR", FuelPolicy.FULLFULL, 127.33d));
        carResults.add(new CarResult("Volkswagen Golf", "GOLDCAR", "CLMR", FuelPolicy.FULLFULL, 54.13d));
        carResults.add(new CarResult("Citroen C4 Grand Picasso", "GOLDCAR", "IVAR", FuelPolicy.FULLFULL, 326.7d));
        carResults.add(new CarResult("Toyota Avensis", "GOLDCAR", "IDAR", FuelPolicy.FULLFULL, 97.31d));
        carResults.add(new CarResult("Ford Focus Estate", "GOLDCAR", "CWMR", FuelPolicy.FULLFULL, 114.01d));
        carResults.add(new CarResult("Volkswagen Touran", "GOLDCAR", "IVMR", FuelPolicy.FULLFULL, 303.43d));
        carResults.add(new CarResult("Citroen DS3", "GOLDCAR", "ESMR", FuelPolicy.FULLFULL, 60d));
        carResults.add(new CarResult("Audi A3", "GOLDCAR", "ICMR", FuelPolicy.FULLFULL, 74.04d));
        carResults.add(new CarResult("Citroen Berlingo", "GOLDCAR", "CMMV", FuelPolicy.FULLFULL, 70.83d));
        carResults.add(new CarResult("Volkswagen Polo", "GOLDCAR", "EDMR", FuelPolicy.FULLFULL, 44.99d));
        carResults.add(new CarResult("Renault Scenic", "GOLDCAR", "JGMR", FuelPolicy.FULLFULL, 120.59d));
        carResults.add(new CarResult("BMW 3 Series", "GOLDCAR", "FDAR", FuelPolicy.FULLFULL, 353.17d));
        carResults.add(new CarResult("Peugeot 107", "GOLDCAR", "MCMR", FuelPolicy.FULLFULL, 39.63d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "GOLDCAR", "SVMR", FuelPolicy.FULLFULL, 509.37d));
        carResults.add(new CarResult("Volkswagen Golf", "GOLDCAR", "CDMR", FuelPolicy.FULLFULL, 49.58d));
        carResults.add(new CarResult("BMW 4 Series Convertible", "MARBESOL", "RTAV", FuelPolicy.FULLEMPTY, 189.85d));
        carResults.add(new CarResult("Renault Megane Convertible", "MARBESOL", "CTMR", FuelPolicy.FULLEMPTY, 59.22d));
        carResults.add(new CarResult("Citroen Berlingo", "MARBESOL", "CMMV", FuelPolicy.FULLEMPTY, 10.53d));
        carResults.add(new CarResult("Ford Focus Estate", "MARBESOL", "CWMR", FuelPolicy.FULLEMPTY, 16.11d));
        carResults.add(new CarResult("Volkswagen Passat Diesel", "MARBESOL", "IDMD", FuelPolicy.FULLEMPTY, 38.15d));
        carResults.add(new CarResult("Renault Clio Estate", "MARBESOL", "EWMR", FuelPolicy.FULLEMPTY, 10.93d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "MARBESOL", "SVMR", FuelPolicy.FULLEMPTY, 108.04d));
        carResults.add(new CarResult("Volkswagen Polo", "MARBESOL", "EDMM", FuelPolicy.FULLEMPTY, 4.8d));
        carResults.add(new CarResult("Ford Galaxy", "MARBESOL", "FVMR", FuelPolicy.FULLEMPTY, 45.07d));
        carResults.add(new CarResult("BMW 3 Series", "MARBESOL", "FDAR", FuelPolicy.FULLEMPTY, 74.03d));
        carResults.add(new CarResult("Volkswagen Touran", "MARBESOL", "IVMR", FuelPolicy.FULLEMPTY, 35.64d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "MARBESOL", "CDMD", FuelPolicy.FULLEMPTY, 8.86d));
        carResults.add(new CarResult("Toyota Yaris", "MARBESOL", "EDAR", FuelPolicy.FULLEMPTY, 16.86d));
        carResults.add(new CarResult("Volkswagen Up", "MARBESOL", "MDMR", FuelPolicy.FULLEMPTY, 4d));
        carResults.add(new CarResult("Nissan Qashqai", "MARBESOL", "IFMR", FuelPolicy.FULLEMPTY, 45.07d));
        carResults.add(new CarResult("Ford Fiesta Diesel", "MARBESOL", "EDMD", FuelPolicy.FULLEMPTY, 5.11d));
        carResults.add(new CarResult("Toyota Avensis", "MARBESOL", "IDMR", FuelPolicy.FULLEMPTY, 36.57d));
        carResults.add(new CarResult("Volkswagen Golf", "MARBESOL", "CDMR", FuelPolicy.FULLEMPTY, 8.05d));
        carResults.add(new CarResult("Volkswagen Golf", "MARBESOL", "CDAR", FuelPolicy.FULLEMPTY, 25.24d));
        carResults.add(new CarResult("Volkswagen Polo", "MARBESOL", "EDMR", FuelPolicy.FULLEMPTY, 4.49d));
        carResults.add(new CarResult("Volkswagen Passat", "MARBESOL", "SDAR", FuelPolicy.FULLEMPTY, 44.14d));
        carResults.add(new CarResult("BMW 3 Series", "MARBESOL", "FDMR", FuelPolicy.FULLEMPTY, 47.55d));
        carResults.add(new CarResult("Mercedes Citan", "MARBESOL", "CMMD", FuelPolicy.FULLEMPTY, 10.53d));
        carResults.add(new CarResult("BMW 4 Series Convertible", "MARBESOL", "RTAV", FuelPolicy.FULLEMPTY, 189.85d));
        carResults.add(new CarResult("Renault Megane Convertible", "MARBESOL", "CTMR", FuelPolicy.FULLEMPTY, 59.22d));
        carResults.add(new CarResult("Citroen Berlingo", "MARBESOL", "CMMV", FuelPolicy.FULLEMPTY, 10.53d));
        carResults.add(new CarResult("Ford Focus Estate", "MARBESOL", "CWMR", FuelPolicy.FULLEMPTY, 16.11d));
        carResults.add(new CarResult("Volkswagen Passat Diesel", "MARBESOL", "IDMD", FuelPolicy.FULLEMPTY, 38.15d));
        carResults.add(new CarResult("Renault Clio Estate", "MARBESOL", "EWMR", FuelPolicy.FULLEMPTY, 10.93d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "MARBESOL", "SVMR", FuelPolicy.FULLEMPTY, 108.04d));
        carResults.add(new CarResult("Volkswagen Polo", "MARBESOL", "EDMM", FuelPolicy.FULLEMPTY, 4.8d));
        carResults.add(new CarResult("Ford Galaxy", "MARBESOL", "FVMR", FuelPolicy.FULLEMPTY, 45.07d));
        carResults.add(new CarResult("BMW 3 Series", "MARBESOL", "FDAR", FuelPolicy.FULLEMPTY, 74.03d));
        carResults.add(new CarResult("Volkswagen Touran", "MARBESOL", "IVMR", FuelPolicy.FULLEMPTY, 35.64d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "MARBESOL", "CDMD", FuelPolicy.FULLEMPTY, 8.86d));
        carResults.add(new CarResult("Toyota Yaris", "MARBESOL", "EDAR", FuelPolicy.FULLEMPTY, 16.86d));
        carResults.add(new CarResult("Volkswagen Up", "MARBESOL", "MDMR", FuelPolicy.FULLEMPTY, 4d));
        carResults.add(new CarResult("Nissan Qashqai", "MARBESOL", "IFMR", FuelPolicy.FULLEMPTY, 45.07d));
        carResults.add(new CarResult("Ford Fiesta Diesel", "MARBESOL", "EDMD", FuelPolicy.FULLEMPTY, 5.11d));
        carResults.add(new CarResult("Toyota Avensis", "MARBESOL", "IDMR", FuelPolicy.FULLEMPTY, 36.57d));
        carResults.add(new CarResult("Volkswagen Golf", "MARBESOL", "CDMR", FuelPolicy.FULLEMPTY, 8.05d));
        carResults.add(new CarResult("Volkswagen Golf", "MARBESOL", "CDAR", FuelPolicy.FULLEMPTY, 25.24d));
        carResults.add(new CarResult("Volkswagen Polo", "MARBESOL", "EDMR", FuelPolicy.FULLEMPTY, 4.49d));
        carResults.add(new CarResult("Volkswagen Passat", "MARBESOL", "SDAR", FuelPolicy.FULLEMPTY, 44.14d));
        carResults.add(new CarResult("BMW 3 Series", "MARBESOL", "FDMR", FuelPolicy.FULLEMPTY, 47.55d));
        carResults.add(new CarResult("Mercedes Citan", "MARBESOL", "CMMD", FuelPolicy.FULLEMPTY, 10.53d));
        carResults.add(new CarResult("BMW 4 Series Convertible", "MARBESOL", "RTAV", FuelPolicy.FULLFULL, 516.52d));
        carResults.add(new CarResult("Renault Megane Convertible", "MARBESOL", "CTMR", FuelPolicy.FULLFULL, 204.47d));
        carResults.add(new CarResult("Citroen Berlingo", "MARBESOL", "CMMV", FuelPolicy.FULLFULL, 78.06d));
        carResults.add(new CarResult("Ford Focus Estate", "MARBESOL", "CWMR", FuelPolicy.FULLFULL, 85.54d));
        carResults.add(new CarResult("Volkswagen Passat Diesel", "MARBESOL", "IDMD", FuelPolicy.FULLFULL, 98.2d));
        carResults.add(new CarResult("Renault Clio Estate", "MARBESOL", "EWMR", FuelPolicy.FULLFULL, 82.37d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "MARBESOL", "SVMR", FuelPolicy.FULLFULL, 231.59d));
        carResults.add(new CarResult("Volkswagen Polo", "MARBESOL", "EDMM", FuelPolicy.FULLFULL, 70.89d));
        carResults.add(new CarResult("Ford Galaxy", "MARBESOL", "FVMR", FuelPolicy.FULLFULL, 213.53d));
        carResults.add(new CarResult("BMW 3 Series", "MARBESOL", "FDAR", FuelPolicy.FULLFULL, 199.93d));
        carResults.add(new CarResult("Volkswagen Touran", "MARBESOL", "IVMR", FuelPolicy.FULLFULL, 168.28d));
        carResults.add(new CarResult("Volkswagen Passat Diesel", "MARBESOL", "IDAD", FuelPolicy.FULLFULL, 127.59d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "MARBESOL", "CDMD", FuelPolicy.FULLFULL, 76.94d));
        carResults.add(new CarResult("Toyota Yaris", "MARBESOL", "EDAR", FuelPolicy.FULLFULL, 91.44d));
        carResults.add(new CarResult("Renault Scenic", "MARBESOL", "JGMR", FuelPolicy.FULLFULL, 86.44d));
        carResults.add(new CarResult("Volkswagen Up", "MARBESOL", "MDMR", FuelPolicy.FULLFULL, 69.93d));
        carResults.add(new CarResult("Nissan Qashqai", "MARBESOL", "IFMR", FuelPolicy.FULLFULL, 88.27d));
        carResults.add(new CarResult("Ford Fiesta Diesel", "MARBESOL", "EDMD", FuelPolicy.FULLFULL, 73.78d));
        carResults.add(new CarResult("Toyota Avensis", "MARBESOL", "IDMR", FuelPolicy.FULLFULL, 95.47d));
        carResults.add(new CarResult("Volkswagen Golf", "MARBESOL", "CDMR", FuelPolicy.FULLFULL, 75.14d));
        carResults.add(new CarResult("Volkswagen Golf", "MARBESOL", "CDAR", FuelPolicy.FULLFULL, 109.5d));
        carResults.add(new CarResult("Volkswagen Polo", "MARBESOL", "EDMR", FuelPolicy.FULLFULL, 70.89d));
        carResults.add(new CarResult("Citroen C4 Cactus", "MARBESOL", "CGAR", FuelPolicy.FULLFULL, 114.03d));
        carResults.add(new CarResult("Volkswagen Passat", "MARBESOL", "SDAR", FuelPolicy.FULLFULL, 123.09d));
        carResults.add(new CarResult("BMW 3 Series", "MARBESOL", "FDMR", FuelPolicy.FULLFULL, 195.43d));
        carResults.add(new CarResult("BMW 1 Series", "MARBESOL", "IDAR", FuelPolicy.FULLFULL, 172.81d));
        carResults.add(new CarResult("Mercedes Citan", "MARBESOL", "CMMD", FuelPolicy.FULLFULL, 78.06d));
        carResults.add(new CarResult("Citroen Berlingo", "RECORD", "CMMV", FuelPolicy.FULLEMPTY, 33.26d));
        carResults.add(new CarResult("Volkswagen Golf", "RECORD", "CDMR", FuelPolicy.FULLEMPTY, 26.52d));
        carResults.add(new CarResult("Nissan Juke", "RECORD", "CFMR", FuelPolicy.FULLEMPTY, 28.64d));
        carResults.add(new CarResult("Toyota Rav4", "RECORD", "IFMR", FuelPolicy.FULLEMPTY, 36.3d));
        carResults.add(new CarResult("Ford Galaxy", "RECORD", "FVMR", FuelPolicy.FULLEMPTY, 154.59d));
        carResults.add(new CarResult("Volkswagen Polo", "RECORD", "EDMR", FuelPolicy.FULLEMPTY, 22.23d));
        carResults.add(new CarResult("Peugeot 107", "RECORD", "MCMR", FuelPolicy.FULLEMPTY, 19.1d));
        carResults.add(new CarResult("Citroen Berlingo", "RECORD", "CMMV", FuelPolicy.FULLEMPTY, 34.8d));
        carResults.add(new CarResult("Ford Galaxy", "RECORD", "FVAR", FuelPolicy.FULLEMPTY, 160.75d));
        carResults.add(new CarResult("Audi A3", "SIXT", "ICMR", FuelPolicy.FULLFULL, 186.37d));
        carResults.add(new CarResult("BMW 2 Series Active Tourer", "SIXT", "JDAR", FuelPolicy.FULLFULL, 239.18d));
        carResults.add(new CarResult("Ford Focus Estate", "SIXT", "CWMR", FuelPolicy.FULLFULL, 222.56d));
        carResults.add(new CarResult("Volkswagen Polo", "SIXT", "EDMR", FuelPolicy.FULLFULL, 128.93d));
        carResults.add(new CarResult("Mercedes A Class", "SIXT", "ICAV", FuelPolicy.FULLFULL, 254.02d));
        carResults.add(new CarResult("Peugeot 107", "SIXT", "MCMR", FuelPolicy.FULLFULL, 97.08d));
        carResults.add(new CarResult("BMW 2 Series Active Tourer", "SIXT", "JDMR", FuelPolicy.FULLFULL, 183.14d));
        carResults.add(new CarResult("Smart Fortwo", "SIXT", "MUMR", FuelPolicy.FULLFULL, 115.76d));
        carResults.add(new CarResult("Volkswagen Golf", "SIXT", "CDMR", FuelPolicy.FULLFULL, 134.45d));
        carResults.add(new CarResult("Opel Corsa", "SIXT", "ECMN", FuelPolicy.FULLFULL, 107.58d));
        carResults.add(new CarResult("Mini Convertible", "SIXT", "NTMR", FuelPolicy.FULLFULL, 248.85d));
        carResults.add(new CarResult("Citroen C4 Cactus", "SIXT", "CGAR", FuelPolicy.FULLFULL, 191.54d));
        carResults.add(new CarResult("Mercedes E Class", "SIXT", "PDAR", FuelPolicy.FULLFULL, 403.22d));
        carResults.add(new CarResult("Toyota Rav4", "SIXT", "IFAR", FuelPolicy.FULLFULL, 328.62d));
        carResults.add(new CarResult("Mercedes E Class", "SIXT", "PDMR", FuelPolicy.FULLFULL, 325.38d));
        carResults.add(new CarResult("Toyota Rav4", "SIXT", "IFMR", FuelPolicy.FULLFULL, 276.73d));
        carResults.add(new CarResult("Volkswagen Passat Estate", "SIXT", "SWMR", FuelPolicy.FULLFULL, 292.78d));
        carResults.add(new CarResult("Ford Galaxy", "SIXT", "FVMR", FuelPolicy.FULLFULL, 692.45d));
        carResults.add(new CarResult("BMW 3 Series", "SIXT", "FDMR", FuelPolicy.FULLFULL, 225.18d));
        carResults.add(new CarResult("BMW 3 Series", "SIXT", "FDAR", FuelPolicy.FULLFULL, 295.22d));
        carResults.add(new CarResult("Renault Scenic", "SIXT", "JGMR", FuelPolicy.FULLFULL, 245.09d));
        carResults.add(new CarResult("Toyota Avensis", "AVIS", "IDMR", FuelPolicy.FULLFULL, 373.69d));
        carResults.add(new CarResult("Opel Astra", "AVIS", "CCMR", FuelPolicy.FULLFULL, 203.32d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "AVIS", "IVAD", FuelPolicy.FULLFULL, 520.49d));
        carResults.add(new CarResult("Mercedes E Class", "AVIS", "PDAR", FuelPolicy.FULLFULL, 948.24d));
        carResults.add(new CarResult("Mercedes E Class", "AVIS", "PDAR", FuelPolicy.FULLFULL, 790.36d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "AVIS", "IVMD", FuelPolicy.FULLFULL, 495.74d));
        carResults.add(new CarResult("Skoda Octavia Diesel", "AVIS", "IDMD", FuelPolicy.FULLFULL, 310.22d));
        carResults.add(new CarResult("Ford Focus Estate", "AVIS", "CWMR", FuelPolicy.FULLFULL, 291.28d));
        carResults.add(new CarResult("Mercedes Viano", "AVIS", "OVAR", FuelPolicy.FULLFULL, 572.44d));
        carResults.add(new CarResult("Ford Galaxy Diesel", "AVIS", "FVMD", FuelPolicy.FULLFULL, 520.49d));
        carResults.add(new CarResult("Peugeot 107", "AVIS", "MCMR", FuelPolicy.FULLFULL, 145.52d));
        carResults.add(new CarResult("Toyota Avensis", "AVIS", "IDAR", FuelPolicy.FULLFULL, 465.34d));
        carResults.add(new CarResult("Volkswagen Polo", "AVIS", "EDMR", FuelPolicy.FULLFULL, 160.73d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "AVIS", "SVMR", FuelPolicy.FULLFULL, 624.38d));
        carResults.add(new CarResult("Mercedes A Class", "AVIS", "ICAV", FuelPolicy.FULLFULL, 310.56d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "AVIS", "CDMD", FuelPolicy.FULLFULL, 258.69d));
        carResults.add(new CarResult("Toyota Avensis", "AVIS", "IDMR", FuelPolicy.FULLFULL, 373.69d));
        carResults.add(new CarResult("Opel Astra", "AVIS", "CCMR", FuelPolicy.FULLFULL, 203.32d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "AVIS", "IVAD", FuelPolicy.FULLFULL, 520.49d));
        carResults.add(new CarResult("Mercedes E Class", "AVIS", "PDAR", FuelPolicy.FULLFULL, 948.24d));
        carResults.add(new CarResult("Mercedes E Class", "AVIS", "PDAR", FuelPolicy.FULLFULL, 790.36d));
        carResults.add(new CarResult("Volkswagen Touran Diesel", "AVIS", "IVMD", FuelPolicy.FULLFULL, 495.74d));
        carResults.add(new CarResult("Skoda Octavia Diesel", "AVIS", "IDMD", FuelPolicy.FULLFULL, 310.22d));
        carResults.add(new CarResult("Ford Focus Estate", "AVIS", "CWMR", FuelPolicy.FULLFULL, 291.28d));
        carResults.add(new CarResult("Mercedes Viano", "AVIS", "OVAR", FuelPolicy.FULLFULL, 572.44d));
        carResults.add(new CarResult("Ford Galaxy Diesel", "AVIS", "FVMD", FuelPolicy.FULLFULL, 520.49d));
        carResults.add(new CarResult("Peugeot 107", "AVIS", "MCMR", FuelPolicy.FULLFULL, 145.52d));
        carResults.add(new CarResult("Toyota Avensis", "AVIS", "IDAR", FuelPolicy.FULLFULL, 465.34d));
        carResults.add(new CarResult("Volkswagen Polo", "AVIS", "EDMR", FuelPolicy.FULLFULL, 160.73d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "AVIS", "SVMR", FuelPolicy.FULLFULL, 624.38d));
        carResults.add(new CarResult("Mercedes A Class", "AVIS", "ICAV", FuelPolicy.FULLFULL, 310.56d));
        carResults.add(new CarResult("Volkswagen Golf Diesel", "AVIS", "CDMD", FuelPolicy.FULLFULL, 258.69d));
        carResults.add(new CarResult("Toyota Avensis", "BUDGET", "IDMR", FuelPolicy.FULLFULL, 211.89d));
        carResults.add(new CarResult("Opel Astra", "BUDGET", "CCMR", FuelPolicy.FULLFULL, 177.15d));
        carResults.add(new CarResult("Volkswagen Golf", "BUDGET", "CDMR", FuelPolicy.FULLFULL, 268.97d));
        carResults.add(new CarResult("Toyota Avensis", "BUDGET", "IDMR", FuelPolicy.FULLFULL, 234.91d));
        carResults.add(new CarResult("Opel Astra", "BUDGET", "CCMR", FuelPolicy.FULLFULL, 196.21d));
        carResults.add(new CarResult("Volkswagen Golf", "BUDGET", "CDMR", FuelPolicy.FULLFULL, 298.48d));
        carResults.add(new CarResult("Toyota Avensis", "BUDGET", "IDMR", FuelPolicy.FULLFULL, 211.89d));
        carResults.add(new CarResult("Opel Astra", "BUDGET", "CCMR", FuelPolicy.FULLFULL, 177.15d));
        carResults.add(new CarResult("Volkswagen Golf", "BUDGET", "CDMR", FuelPolicy.FULLFULL, 268.97d));
        carResults.add(new CarResult("Toyota Avensis", "BUDGET", "IDMR", FuelPolicy.FULLFULL, 211.89d));
        carResults.add(new CarResult("Opel Astra", "BUDGET", "CCMR", FuelPolicy.FULLFULL, 177.15d));
        carResults.add(new CarResult("Volkswagen Golf", "BUDGET", "CDMR", FuelPolicy.FULLFULL, 268.97d));
        carResults.add(new CarResult("Toyota Avensis", "BUDGET", "IDMR", FuelPolicy.FULLFULL, 211.89d));
        carResults.add(new CarResult("Opel Astra", "BUDGET", "CCMR", FuelPolicy.FULLFULL, 177.15d));
        carResults.add(new CarResult("Volkswagen Golf", "BUDGET", "CDMR", FuelPolicy.FULLFULL, 268.97d));
        carResults.add(new CarResult("Ford Focus Estate", "DELPASO", "CWMR", FuelPolicy.FULLEMPTY, 31.35d));
        carResults.add(new CarResult("Volkswagen Up", "DELPASO", "MDMR", FuelPolicy.FULLEMPTY, 5.92d));
        carResults.add(new CarResult("Volkswagen Golf", "DELPASO", "CDMR", FuelPolicy.FULLEMPTY, 11.49d));
        carResults.add(new CarResult("Toyota Rav4", "DELPASO", "IFMR", FuelPolicy.FULLEMPTY, 41.16d));
        carResults.add(new CarResult("Volkswagen Polo", "DELPASO", "EDMR", FuelPolicy.FULLEMPTY, 6.23d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "DELPASO", "SVMR", FuelPolicy.FULLEMPTY, 121.26d));
        carResults.add(new CarResult("Peugeot 107", "DELPASO", "MCMR", FuelPolicy.FULLEMPTY, 5.92d));
        carResults.add(new CarResult("Peugeot 107", "THRIFTY", "MCMR", FuelPolicy.FULLFULL, 67.03d));
        carResults.add(new CarResult("Peugeot 107", "THRIFTY", "MCMR", FuelPolicy.FULLFULL, 67.03d));
        carResults.add(new CarResult("Renault Clio Estate", "FIREFLY", "EWMR", FuelPolicy.FULLEMPTY, 45.16d));
        carResults.add(new CarResult("Peugeot 107", "FIREFLY", "MCMR", FuelPolicy.FULLEMPTY, 26.57d));
        carResults.add(new CarResult("Volkswagen Polo", "FIREFLY", "EDMR", FuelPolicy.FULLEMPTY, 29.79d));
        carResults.add(new CarResult("Citroen Berlingo", "FIREFLY", "CMMV", FuelPolicy.FULLEMPTY, 35.67d));
        carResults.add(new CarResult("Volkswagen Touran", "FIREFLY", "IVMR", FuelPolicy.FULLEMPTY, 125.92d));
        carResults.add(new CarResult("Volkswagen Golf", "FIREFLY", "CDMR", FuelPolicy.FULLEMPTY, 33.84d));
        carResults.add(new CarResult("Peugeot 107", "HERTZ", "MCMR", FuelPolicy.FULLFULL, 67.98d));
        carResults.add(new CarResult("Peugeot 107", "HERTZ", "MCMR", FuelPolicy.FULLFULL, 60.34d));
        carResults.add(new CarResult("Peugeot 107", "ENTERPRISE", "MCMR", FuelPolicy.FULLFULL, 78.1d));
        carResults.add(new CarResult("Volkswagen Passat", "ENTERPRISE", "SDMR", FuelPolicy.FULLFULL, 206.5d));
        carResults.add(new CarResult("Volkswagen Polo", "ENTERPRISE", "EDMR", FuelPolicy.FULLFULL, 105.51d));
        carResults.add(new CarResult("Ford Galaxy", "ENTERPRISE", "FVMR", FuelPolicy.FULLFULL, 512.95d));
        carResults.add(new CarResult("Volkswagen Touran", "ENTERPRISE", "IVAR", FuelPolicy.FULLFULL, 392.35d));
        carResults.add(new CarResult("Citroen Berlingo", "ENTERPRISE", "CMMV", FuelPolicy.FULLFULL, 212.23d));
        carResults.add(new CarResult("Toyota Avensis", "ENTERPRISE", "IDMR", FuelPolicy.FULLFULL, 124.84d));
        carResults.add(new CarResult("Volkswagen Golf", "ENTERPRISE", "CDAR", FuelPolicy.FULLFULL, 516.28d));
        carResults.add(new CarResult("Renault Scenic", "ENTERPRISE", "JGMR", FuelPolicy.FULLFULL, 268.42d));
        carResults.add(new CarResult("Toyota Avensis", "ENTERPRISE", "IDAR", FuelPolicy.FULLFULL, 413.05d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "ENTERPRISE", "SVMR", FuelPolicy.FULLFULL, 579.11d));
        carResults.add(new CarResult("Renault Scenic", "ENTERPRISE", "IMMR", FuelPolicy.FULLFULL, 224.74d));
        carResults.add(new CarResult("Volkswagen Golf", "ENTERPRISE", "CDMR", FuelPolicy.FULLFULL, 142.05d));
        carResults.add(new CarResult("Renault Scenic", "RHODIUM", "JGMR", FuelPolicy.FULLFULL, 180.47d));
        carResults.add(new CarResult("BMW 3 Series", "RHODIUM", "FDAR", FuelPolicy.FULLFULL, 409.68d));
        carResults.add(new CarResult("Ford Focus Estate", "RHODIUM", "CWMR", FuelPolicy.FULLFULL, 177.09d));
        carResults.add(new CarResult("Citroen DS3", "RHODIUM", "ESMR", FuelPolicy.FULLFULL, 116.51d));
        carResults.add(new CarResult("Volkswagen Golf", "RHODIUM", "CDAR", FuelPolicy.FULLFULL, 243.55d));
        carResults.add(new CarResult("Volkswagen Golf", "RHODIUM", "CDMR", FuelPolicy.FULLFULL, 104.53d));
        carResults.add(new CarResult("Toyota Avensis", "RHODIUM", "IDMR", FuelPolicy.FULLFULL, 300.05d));
        carResults.add(new CarResult("Audi A3", "RHODIUM", "ICMR", FuelPolicy.FULLFULL, 130.54d));
        carResults.add(new CarResult("Citroen Berlingo", "RHODIUM", "CMMV", FuelPolicy.FULLFULL, 114.01d));
        carResults.add(new CarResult("Volkswagen Polo", "RHODIUM", "EDMR", FuelPolicy.FULLFULL, 92.9d));
        carResults.add(new CarResult("Ford Galaxy", "RHODIUM", "FVMR", FuelPolicy.FULLFULL, 509.37d));
        carResults.add(new CarResult("Volkswagen Golf", "RHODIUM", "CLMR", FuelPolicy.FULLFULL, 109.76d));
        carResults.add(new CarResult("Volkswagen Touran", "RHODIUM", "IVMR", FuelPolicy.FULLFULL, 359.93d));
        carResults.add(new CarResult("Peugeot 107", "RHODIUM", "MCMR", FuelPolicy.FULLFULL, 87.36d));
        carResults.add(new CarResult("Volkswagen Touran", "RHODIUM", "IVAR", FuelPolicy.FULLFULL, 383.03d));
        carResults.add(new CarResult("Mercedes Vito Traveliner", "RHODIUM", "SVMR", FuelPolicy.FULLFULL, 565.88d));
        carResults.add(new CarResult("Toyota Avensis", "RHODIUM", "IDAR", FuelPolicy.FULLFULL, 153.82d));
        carResults.add(new CarResult("Toyota Rav4", "FLIZZR", "IFMR", FuelPolicy.FULLEMPTY, 75.93d));
        carResults.add(new CarResult("Opel Corsa", "FLIZZR", "EBMN", FuelPolicy.FULLEMPTY, 49.29d));
        carResults.add(new CarResult("Peugeot 2008", "FLIZZR", "EGMR", FuelPolicy.FULLEMPTY, 78.43d));
        carResults.add(new CarResult("Citroen C3 Picasso", "FLIZZR", "EMMV", FuelPolicy.FULLEMPTY, 75.93d));
        carResults.add(new CarResult("Volkswagen Golf", "FLIZZR", "CDMR", FuelPolicy.FULLEMPTY, 87.91d));
        carResults.add(new CarResult("Volkswagen Polo", "FLIZZR", "EDMR", FuelPolicy.FULLEMPTY, 49.29d));
        carResults.add(new CarResult("Citroen DS3", "FLIZZR", "ESMR", FuelPolicy.FULLEMPTY, 53.56d));
        carResults.add(new CarResult("Citroen C1", "FLIZZR", "MBMR", FuelPolicy.FULLEMPTY, 42.54d));
        carResults.add(new CarResult("Toyota Rav4", "FLIZZR", "IFMR", FuelPolicy.FULLFULL, 87.73d));
        carResults.add(new CarResult("Opel Corsa", "FLIZZR", "EBMN", FuelPolicy.FULLFULL, 56.51d));
        carResults.add(new CarResult("Peugeot 2008", "FLIZZR", "EGMR", FuelPolicy.FULLFULL, 90.23d));
        carResults.add(new CarResult("Citroen C3 Picasso", "FLIZZR", "EMMV", FuelPolicy.FULLFULL, 87.73d));
        carResults.add(new CarResult("Volkswagen Golf", "FLIZZR", "CDMR", FuelPolicy.FULLFULL, 101.62d));
        carResults.add(new CarResult("Volkswagen Polo", "FLIZZR", "EDMR", FuelPolicy.FULLFULL, 56.51d));
        carResults.add(new CarResult("Citroen Berlingo", "FLIZZR", "CMMV", FuelPolicy.FULLFULL, 113.91d));
        carResults.add(new CarResult("Citroen DS3", "FLIZZR", "ESMR", FuelPolicy.FULLFULL, 61.44d));
        carResults.add(new CarResult("Volkswagen Touran", "FLIZZR", "IVMR", FuelPolicy.FULLFULL, 159.66d));
        carResults.add(new CarResult("Citroen C1", "FLIZZR", "MBMR", FuelPolicy.FULLFULL, 49.08d));
        return carResults;
    }
}
